declare namespace _default {
    const schedulerWidth: string;
    const besidesWidth: number;
    const schedulerMaxHeight: number;
    const tableHeaderHeight: number;
    const agendaResourceTableWidth: number;
    const agendaMaxEventWidth: number;
    const dayResourceTableWidth: number;
    const weekResourceTableWidth: string;
    const monthResourceTableWidth: number;
    const quarterResourceTableWidth: number;
    const yearResourceTableWidth: number;
    const customResourceTableWidth: number;
    const dayCellWidth: number;
    const weekCellWidth: string;
    const monthCellWidth: number;
    const quarterCellWidth: number;
    const yearCellWidth: number;
    const customCellWidth: number;
    const dayMaxEvents: number;
    const weekMaxEvents: number;
    const monthMaxEvents: number;
    const quarterMaxEvents: number;
    const yearMaxEvents: number;
    const customMaxEvents: number;
    const eventItemHeight: number;
    const eventItemLineHeight: number;
    const nonAgendaSlotMinHeight: number;
    const dayStartFrom: number;
    const dayStopTo: number;
    const defaultEventBgColor: string;
    const selectedAreaColor: string;
    const nonWorkingTimeHeadColor: string;
    const nonWorkingTimeHeadBgColor: string;
    const nonWorkingTimeBodyBgColor: string;
    const summaryColor: string;
    const summaryPos: number;
    const groupOnlySlotColor: string;
    const startResizable: boolean;
    const endResizable: boolean;
    const movable: boolean;
    const creatable: boolean;
    const crossResourceMove: boolean;
    const checkConflict: boolean;
    const scrollToSpecialMomentEnabled: boolean;
    const eventItemPopoverEnabled: boolean;
    const calendarPopoverEnabled: boolean;
    const recurringEventsEnabled: boolean;
    const headerEnabled: boolean;
    const displayWeekend: boolean;
    const relativeMove: boolean;
    const defaultExpanded: boolean;
    const resourceName: string;
    const taskName: string;
    const agendaViewHeader: string;
    const addMorePopoverHeaderFormat: string;
    const eventItemPopoverDateFormat: string;
    const nonAgendaDayCellHeaderFormat: string;
    const nonAgendaOtherCellHeaderFormat: string;
    const minuteStep: number;
    const views: {
        viewName: string;
        viewType: number;
        showAgenda: boolean;
        isEventPerspective: boolean;
    }[];
}
export default _default;
