export default DemoData;
declare namespace DemoData {
    const resources: ({
        id: string;
        name: string;
        groupOnly: boolean;
        parentId?: undefined;
    } | {
        id: string;
        name: string;
        parentId: string;
        groupOnly?: undefined;
    } | {
        id: string;
        name: string;
        groupOnly?: undefined;
        parentId?: undefined;
    })[];
    const events: ({
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        bgColor: string;
        showPopover: boolean;
        resizable?: undefined;
        movable?: undefined;
        startResizable?: undefined;
        endResizable?: undefined;
        rrule?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        resizable: boolean;
        bgColor?: undefined;
        showPopover?: undefined;
        movable?: undefined;
        startResizable?: undefined;
        endResizable?: undefined;
        rrule?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        movable: boolean;
        bgColor?: undefined;
        showPopover?: undefined;
        resizable?: undefined;
        startResizable?: undefined;
        endResizable?: undefined;
        rrule?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        startResizable: boolean;
        bgColor?: undefined;
        showPopover?: undefined;
        resizable?: undefined;
        movable?: undefined;
        endResizable?: undefined;
        rrule?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        endResizable: boolean;
        bgColor?: undefined;
        showPopover?: undefined;
        resizable?: undefined;
        movable?: undefined;
        startResizable?: undefined;
        rrule?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        bgColor?: undefined;
        showPopover?: undefined;
        resizable?: undefined;
        movable?: undefined;
        startResizable?: undefined;
        endResizable?: undefined;
        rrule?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        bgColor: string;
        showPopover?: undefined;
        resizable?: undefined;
        movable?: undefined;
        startResizable?: undefined;
        endResizable?: undefined;
        rrule?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        movable: boolean;
        resizable: boolean;
        bgColor: string;
        showPopover?: undefined;
        startResizable?: undefined;
        endResizable?: undefined;
        rrule?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        rrule: string;
        bgColor: string;
        showPopover?: undefined;
        resizable?: undefined;
        movable?: undefined;
        startResizable?: undefined;
        endResizable?: undefined;
    })[];
    const eventsForTaskView: ({
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        bgColor: string;
        groupId: number;
        groupName: string;
        resizable?: undefined;
        movable?: undefined;
        startResizable?: undefined;
        endResizable?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        resizable: boolean;
        groupId: number;
        groupName: string;
        bgColor?: undefined;
        movable?: undefined;
        startResizable?: undefined;
        endResizable?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        movable: boolean;
        groupId: number;
        groupName: string;
        bgColor?: undefined;
        resizable?: undefined;
        startResizable?: undefined;
        endResizable?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        startResizable: boolean;
        groupId: number;
        groupName: string;
        bgColor?: undefined;
        resizable?: undefined;
        movable?: undefined;
        endResizable?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        endResizable: boolean;
        groupId: number;
        groupName: string;
        bgColor?: undefined;
        resizable?: undefined;
        movable?: undefined;
        startResizable?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        groupId: number;
        groupName: string;
        bgColor?: undefined;
        resizable?: undefined;
        movable?: undefined;
        startResizable?: undefined;
        endResizable?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        movable: boolean;
        resizable: boolean;
        bgColor: string;
        groupId: number;
        groupName: string;
        startResizable?: undefined;
        endResizable?: undefined;
    })[];
    const eventsForCustomEventStyle: ({
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        bgColor: string;
        type: number;
        resizable?: undefined;
        movable?: undefined;
        startResizable?: undefined;
        endResizable?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        resizable: boolean;
        type: number;
        bgColor?: undefined;
        movable?: undefined;
        startResizable?: undefined;
        endResizable?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        movable: boolean;
        type: number;
        bgColor?: undefined;
        resizable?: undefined;
        startResizable?: undefined;
        endResizable?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        startResizable: boolean;
        type: number;
        bgColor?: undefined;
        resizable?: undefined;
        movable?: undefined;
        endResizable?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        endResizable: boolean;
        type: number;
        bgColor?: undefined;
        resizable?: undefined;
        movable?: undefined;
        startResizable?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        type: number;
        bgColor?: undefined;
        resizable?: undefined;
        movable?: undefined;
        startResizable?: undefined;
        endResizable?: undefined;
    } | {
        id: number;
        start: string;
        end: string;
        resourceId: string;
        title: string;
        movable: boolean;
        resizable: boolean;
        bgColor: string;
        type: number;
        startResizable?: undefined;
        endResizable?: undefined;
    })[];
}
